# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "trusty"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.provision "file", source: "sagan.upstart", destination: "sagan.upstart"
  config.vm.provision "file", source: "barnyard2.upstart", destination: "barnyard2.upstart"
  config.vm.provision "file", source: "barnyard2-sagan.conf", destination: "barnyard2-sagan.conf"
  config.vm.provision "file", source: "rsyslog-sagan.conf", destination: "rsyslog-sagan.conf"
  config.vm.provision "shell", path:  "provision.sh"

  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # config.vm.synced_folder "../data", "/vagrant_data"

   config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
      vb.name = "sagan"
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", 1]
   end

end
