# -*- mode: ruby -*-
# vi: set ft=ruby :

# Install dependencies
$install = <<SCRIPT
add-apt-repository ppa:agent-8131/ppa
apt-get update
apt-get -y install cmake make gcc g++ flex bison libpcap-dev libssl-dev python-dev swig zlib1g-dev libmagic-dev
apt-get -y install tcpreplay
SCRIPT
# libgoogle-perftools-dev

$keys = <<SCRIPT
mkdir /root/.ssh && sudo chown root:root /root/.ssh && sudo chmod 0600 /root/.ssh
install -o root -g root -m 400 /home/vagrant/.ssh/insecure-ssh-key.pub /root/.ssh/authorized_keys
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "trusty"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.define "manager" do |manager|
    manager.vm.hostname = "manager.bro.org"
    manager.vm.network "private_network", ip: "10.1.1.10", :netmask => "255.255.255.0", :adapter => 2
    manager.vm.provision "file", source: "insecure-ssh-key", destination: "~/.ssh/id_rsa"
    manager.vm.provision "file", source: "node.cfg", destination: "node.cfg"
    # Set to args to "latest" or two-digit version number e.g. "2.2"
    manager.vm.provision "shell", path: "provision-manager.sh", privileged: "true", args: "latest"
    manager.vm.provider "virtualbox" do |vb|
      vb.name = "bro-manager"
      vb.gui = false
      vb.memory = 1024
    end
  end

  config.vm.define "node1" do |node1|
    node1.vm.hostname = "node1.bro.org"
    node1.vm.network "private_network", ip: "10.1.1.20", :netmask => "255.255.255.0", :adapter => 2
    node1.vm.provision "file", source: "insecure-ssh-key.pub", destination: "~/.ssh/insecure-ssh-key.pub"
    node1.vm.provision "shell", inline: $keys
    node1.vm.provision "shell", inline: $install
    node1.vm.provision "file", source: "dissector_fuzz.sh", destination: "dissector_fuzz.sh"
    node1.vm.provider "virtualbox" do |v|
      v.name = "bro-node1"
      v.gui = false
      v.memory = 1024
    end
  end

  config.vm.define "node2" do |node2|
    node2.vm.hostname = "node2.bro.org"
    node2.vm.network "private_network", ip: "10.1.1.30", :netmask => "255.255.255.0", :adapter => 2
    node2.vm.provision "file", source: "insecure-ssh-key.pub", destination: "~/.ssh/insecure-ssh-key.pub"
    node2.vm.provision "shell", inline: $keys
    node2.vm.provision "shell", inline: $install
    node2.vm.provision "file", source: "dissector_fuzz.sh", destination: "dissector_fuzz.sh"
    node2.vm.provider "virtualbox" do |v|
      v.name = "bro-node2"
      v.gui = false
      v.memory = 1024
    end
  end

end
