# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "trusty"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.network "public_network", bridge: 'en0: Ethernet Alias'
  config.vm.provision "file", source: "ks.cfg", destination: "ks.cfg"
  config.vm.provision "file", source: "tftpd-hpa", destination: "tftpd-hpa"
  config.vm.provision "shell", path: "provision.sh", args: "http://releases.ubuntu.com/14.04/ubuntu-14.04.1-server-amd64.iso"

  config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "pxe"
      vb.customize ["modifyvm", :id, "--memory", "256"]
      vb.customize ["modifyvm", :id, "--cpus", 1]
   end

end
