# Bro Sandbox - Bro 2.3
#
# VERSION               1.0.5
FROM      ubuntu
MAINTAINER Jon Schipp <jonschipp@gmail.com>
RUN apt-get update
RUN apt-get install -y build-essential cmake make gcc g++ flex bison libpcap-dev libgeoip-dev libssl-dev python-dev zlib1g-dev libmagic-dev swig2.0 wget
RUN apt-get install -y gawk
RUN adduser --disabled-password --gecos "" demo
RUN su -l -c 'wget http://www.bro.org/downloads/release/bro-2.3.tar.gz && tar -xvzf bro-2.3.tar.gz && cd bro-2.3 && ./configure && make' demo
RUN cd /home/demo/bro-2.3 && make install
RUN rm -f /home/demo/bro-2.3.tar.gz
RUN echo "PATH=$PATH:/usr/local/bro/bin/" > /etc/profile.d/bro.sh && chmod 555 /etc/profile.d/bro.sh
RUN echo "export TMOUT=1800; readonly TMOUT" > /etc/profile.d/timeout.sh && chmod 555 /etc/profile.d/timeout.sh
RUN su -l -c 'ln -s /exercises exercises' demo
# Uncomment if you would like to be able to run BroCtl with sudo (broctl exec can be dangerous)
#RUN echo "demo ALL=(root) NOPASSWD:/usr/local/bro/bin/broctl" > /etc/sudoers.d/bro
#RUN chmod 0440 /etc/sudoers.d/bro && chown root:root /etc/sudoers.d/bro
