# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "trusty"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.provision "file",  source: "sandbox.cron",                  destination: "sandbox.cron"
  config.vm.provision "file",  source: "etc.default.docker",            destination: "etc.default.docker"
  config.vm.provision "file",  source: "scripts/sandbox_login", 	destination: "sandbox_login"
  config.vm.provision "file",  source: "scripts/sandbox_shell",         destination: "sandbox_shell"
  config.vm.provision "file",  source: "scripts/disk_limit",            destination: "disk_limit"
  config.vm.provision "file",  source: "scripts/remove_old_containers", destination: "remove_old_containers"
  config.vm.provision "file",  source: "scripts/remove_old_users",      destination: "remove_old_users"
  config.vm.provision "shell", path:   "provision.sh"

  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # config.vm.synced_folder "../data", "/vagrant_data"

   config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
      vb.name = "bro-sandbox"
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", 1]
   end

end
