# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "trusty"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"
  config.vm.provision "shell", path:   "provision.sh"
  config.vm.network "forwarded_port", protocol: "udp", guest: 25826, host: 25826
  config.vm.network "forwarded_port", protocol: "tcp", guest: 80, host: 8888
  config.vm.network "private_network", ip: "10.1.1.15", :netmask => "255.255.255.0", :adapter => 2
  # config.vm.synced_folder "../data", "/vagrant_data"

   config.vm.provider "virtualbox" do |vb|
  #   vb.gui = true
      vb.name = "collectd"
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpus", 1]
   end

end
